### PR TITLE
Carps and Tables

### PR DESCRIPTION
**Pull request by valzargaming**
Carps can now pass under tables.

### CODE REVIEW

**Comment by Davnik** [comment]
Is it possible to have them pass over tables, or is it easier to just pass them under tables?

**Comment by valzargaming** [comment]
It's basically the same thing, one would require a check when on top of table to be placed on a layer above it. Too much snowflaking in the code though, too many carp would lag like hell.

**Comment by berkbuzcu** [comment]
Have you tested this? When I did this, it didn't work.

**Comment by Moraak** [comment]
This indeed does not work.

**Pull request closed without merging**
