### PR TITLE
Doubles de/construction time for r_walls

### PR DESCRIPTION
**Pull request by valzargaming**
Hopefully should make reinforced walls a little bit more robust.

### CODE REVIEW

**Comment by Davnik** [comment]
Any changes to the construction/deconstruction of barriers should be put on hold until we've made all the changes we will, and likely had a discussion about whether or not or to what extent we want to implement this change. I've heard opinions from both sides, so we aren't in consensus.

**Comment by Moraak** [comment]
Everything checks out and will work fine, except all welding interactions should be doubled not just the reinforced walls. Also please do not push to master, only push to Dev for that reason I'm closing this.

**Comment by valzargaming** [comment]
Those welding changes will have to be done file-per-file, such as in wall.dm, portable_turret.dm, firelock.dm  (after extensive bug testing), as well as in other files that use if(do_after()user, #) strings, which will come in later pull requests. This pull request should be merged to dev and tested before final merge to master.

**Comment by Moraak** [comment]
The only problem is, you've tried to merge into master and I cant redirect the pull request to the dev branch.

**Pull request closed without merging**
